### ISSUE TITLE
Error during migration

### ISSUE THREAD

**Issue by CrazyChief** [infoweb-internet-solutions/yii2-cms-pages#19]
Hello!)
After starting execution of migration i had this error log in console:

`c:\OpenServer\domains\testyii>yii migrate/up --migrationPath=@infoweb/pages/migrations
Yii Migration Tool (based on Yii v2.0.8)

Creating migration history table "migration"...Done.
Total 4 new migrations to be applied:
        m140701_090001_init
        m141001_132609_add_default_permissions
        m150420_075510_add_public_column
        m150528_073125_add_slider_field

Apply the above migrations? (yes|no) [no]:y
**\* applying m140701_090001_init
    > create table {{%pages}} ... done (time: 0.016s)
    > create index template_id on {{%pages}} (template_id) ... done (time: 0.015s)
    > create table {{%pages_lang}} ... done (time: 0.010s)
    > add primary key page_id_language on {{%pages_lang}} (page_id,language) ... done (time: 0.017s)
    > create index language on {{%pages_lang}} (language) ... done (time: 0.016s)
    > add foreign key FK_PAGES_LANG_PAGE_ID: {{%pages_lang}} (page_id) references {{%pages}} (id) ... done (time: 0.013s)
    > create table {{%page_templates}} ... done (time: 0.009s)
    > insert into {{%page_templates}} ... done (time: 0.027s)
**\* applied m140701_090001_init (time: 0.153s)

**\* applying m141001_132609_add_default_permissions
    > insert into {{%auth_item}} ...Exception 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'showPagesModule' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `auth_item` (`name`, `type`, `description`, `created_at`, `updated_at`) VALUES ('showPagesModule', 2, 'Show pages module in main-menu', 1467602990, 1467602990)'

in C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\db\Schema.php:633

Error Info:
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry 'showPagesModule' for key 'PRIMARY'
)

Stack trace:
#0 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\db\Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `au...')
#1 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\db\Migration.php(189): yii\db\Command->execute()
#2 C:\OpenServer\domains\testyii\vendor\infoweb-internet-solutions\yii2-cms-pages\migrations\m141001_132609_add_default_permissions.php(17): yii\db\Migration->insert('{{%auth_item}}', Array)
#3 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): m141001_132609_add_default_permissions->up()
#4 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m141001_132609_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#7 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('up', Array)
#9 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
#10 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\Application.php(176): yii\base\Module->runAction('migrate/up', Array)
#11 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#12 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request)) #13 C:\OpenServer\domains\testyii\yii(20): yii\base\Application->run()
#14 {main}`

What is the problem can be?

**Comment by kurt0015** [comment]
Did you drop the table (migrations)? It seems like you try to run this migration for the second time.

**Option 1**
Drop all tables for this module and rerun migrations.

**Option2**
Do a migration down it will drop showPagesModule from the database table:
`yii migrate/down --migrationPath=@infoweb/pages/migrations`

And then rerun:
`yii migrate/up --migrationPath=@infoweb/pages/migrations`

**Comment by CrazyChief** [comment]
It doesn't work:

`c:\OpenServer\domains\testyii>yii migrate/down --migrationPath=@infoweb/pages/migrations
Yii Migration Tool (based on Yii v2.0.8)

Creating migration history table "migration"...Done.
No migration has been done before.

c:\OpenServer\domains\testyii>yii migrate/up --migrationPath=@infoweb/pages/migrations
Yii Migration Tool (based on Yii v2.0.8)

Total 4 new migrations to be applied:
        m140701_090001_init
        m141001_132609_add_default_permissions
        m150420_075510_add_public_column
        m150528_073125_add_slider_field

Apply the above migrations? (yes|no) [no]:y
*** applying m140701_090001_init
    > create table {{%pages}} ... done (time: 0.014s)
    > create index template_id on {{%pages}} (template_id) ... done (time: 0.014s)
    > create table {{%pages_lang}} ... done (time: 0.009s)
    > add primary key page_id_language on {{%pages_lang}} (page_id,language) ... done (time: 0.016s)
    > create index language on {{%pages_lang}} (language) ... done (time: 0.015s)
    > add foreign key FK_PAGES_LANG_PAGE_ID: {{%pages_lang}} (page_id) references {{%pages}} (id) ... done (time: 0.014s)
    > create table {{%page_templates}} ... done (time: 0.008s)
    > insert into {{%page_templates}} ... done (time: 0.026s)
*** applied m140701_090001_init (time: 0.147s)

*** applying m141001_132609_add_default_permissions
    > insert into {{%auth_item}} ...Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.auth_item' doesn't exist
The SQL being executed was: INSERT INTO `auth_item` (`name`, `type`, `description`, `created_at`, `updated_at`) VALUES ('showPagesModule', 2, 'Show pages module in main-menu', 1467640744, 1467640744)'

in C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\db\Schema.php:633

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'testyii.auth_item' doesn't exist
)

Stack trace:
#0 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\db\Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `au...')

#1 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\db\Migration.php(189): yii\db\Command->execute()
#2 C:\OpenServer\domains\testyii\vendor\infoweb-internet-solutions\yii2-cms-pages\migrations\m141001_132609_add_default_permissions.php(17): yii\db\Migration->insert('{{%auth_item}}', Array)
#3 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): m141001_132609_add_default_permissions->up()

#4 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m141001_132609_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#7 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('up', Array)
#9 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
#10 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\Application.php(176): yii\base\Module->runAction('migrate/up', Array)
#11 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#12 C:\OpenServer\domains\testyii\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request)) #13 C:\OpenServer\domains\testyii\yii(20): yii\base\Application->run()
#14 {main}

c:\OpenServer\domains\testyii>`

**Comment by CrazyChief** [comment]
Does it work on default yii2 or it yii2-cms installation needed?

**Comment by kurt0015** [comment]
The installation guide can be found here:
[https://github.com/infoweb-internet-solutions/yii2-cms](https://github.com/infoweb-internet-solutions/yii2-cms)

The package yii2-cms is required. We will add this dependency a.s.a.p. in our composer file.

I think you removed the migration table in your database. That's why `migrate/down` doesn't do anything.
